### ISSUE TITLE
Field Records do not show all correct sources

### ISSUE THREAD

**Issue by cglatot** [mattantonelli/ffxiv-collect#10]
Hi, on the Field Records page (https://ffxivcollect.com/records) I have noticed that the "Source" list does not list all possible sources. For example, number 14, Saurtavoir, shows "of steel and flame" and "and the flames went higher". However, you can also get this note from "unrest for the wicked" and "help wanted".

There are likely other ones on the page that are missing sources for the notes. You can find an updated list here: https://ffxiv.consolegameswiki.com/wiki/Field_Records

**Comment by mattantonelli** [comment]
Hi there. Due to the highly contentious nature of record sources, screenshots are required for all record source reports.

Sources should also be shared via the official [Discord](https://discord.gg/DkYqtWWpUr). This helps ensure transparency and accountability, and it's where my content moderators will be able to see and update them.

**Comment by cglatot** [comment]
Ah okay, thanks. I don't have those myself so I'll just close this.
